name: rdcircuitry

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend ETL service
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - "4000:4000"
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./logs:/app/logs
      - ./backend/global-bundle.pem:/app/backend/global-bundle.pem:ro
      - ./backend/src/data:/app/backend/src/data:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 