name: rdcircuitry

services:
  # Frontend service
  frontend:
    image: kmxiaaw/rdcircuitry:frontend-v1.4.2
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend ETL service
  backend:
    image: kmxiaaw/rdcircuitry:backend-v1.4.2
    ports:
      - "4000:4000"
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      # CORS Configuration
      - SERVER_IP=137.184.14.201
      - PRODUCTION_DOMAIN=rdcircuitry.com
      - PRODUCTION_URL=https://rdcircuitry.com
      # Override with environment variables from .env file if they exist
    volumes:
      - ./logs:/app/logs
      - ./backend/global-bundle.pem:/app/backend/global-bundle.pem:ro
      - ./backend/src/data:/app/backend/src/data:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge